-- Table Registry: stores metadata about registered tables
CREATE TABLE IF NOT EXISTS TABLE_REGISTRY (
    TABLE_NAME  VARCHAR(128) NOT NULL PRIMARY KEY,
    DESCRIPTION VARCHAR(500),
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Column Registry: stores column definitions for registered tables
CREATE TABLE IF NOT EXISTS COLUMN_REGISTRY (
    TABLE_NAME   VARCHAR(128) NOT NULL,
    COLUMN_NAME  VARCHAR(128) NOT NULL,
    DATA_TYPE    VARCHAR(64)  NOT NULL,
    DESCRIPTION  VARCHAR(500),
    NULLABLE     BOOLEAN DEFAULT TRUE,
    PRIMARY_KEY  BOOLEAN DEFAULT FALSE,
    ORDINAL      INT     DEFAULT 0,
    PRIMARY KEY (TABLE_NAME, COLUMN_NAME),
    FOREIGN KEY (TABLE_NAME) REFERENCES TABLE_REGISTRY(TABLE_NAME) ON DELETE CASCADE
);

-- Tool Registry: stores dynamic MCP tool definitions
CREATE TABLE IF NOT EXISTS TOOL_REGISTRY (
    TOOL_NAME   VARCHAR(128) NOT NULL PRIMARY KEY,
    DESCRIPTION VARCHAR(500) NOT NULL,
    SQL_QUERY   VARCHAR(4000) NOT NULL,
    ACTIVE      BOOLEAN DEFAULT TRUE,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tool Parameter Registry: stores parameter definitions for tools
CREATE TABLE IF NOT EXISTS TOOL_PARAMETER (
    TOOL_NAME   VARCHAR(128) NOT NULL,
    PARAM_NAME  VARCHAR(128) NOT NULL,
    PARAM_TYPE  VARCHAR(20)  NOT NULL DEFAULT 'string',
    DESCRIPTION VARCHAR(500),
    REQUIRED    BOOLEAN DEFAULT FALSE,
    ORDINAL     INT DEFAULT 0,
    PRIMARY KEY (TOOL_NAME, PARAM_NAME),
    FOREIGN KEY (TOOL_NAME) REFERENCES TOOL_REGISTRY(TOOL_NAME) ON DELETE CASCADE
);

-- Example table: CUSTOMERS
CREATE TABLE IF NOT EXISTS CUSTOMERS (
    ID    INT PRIMARY KEY AUTO_INCREMENT,
    NAME  VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(200),
    CITY  VARCHAR(100)
);

-- Example table: ORDERS
CREATE TABLE IF NOT EXISTS ORDERS (
    ID          INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT NOT NULL,
    PRODUCT     VARCHAR(200) NOT NULL,
    AMOUNT      DECIMAL(10,2) NOT NULL,
    ORDER_DATE  DATE DEFAULT CURRENT_DATE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
);
